# Generated by Django 4.1.2 on 2022-10-05 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EwaEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('lc_name', models.CharField(max_length=50)),
                ('event_name', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('price', models.IntegerField()),
                ('delegates_number', models.IntegerField()),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
