# Generated by Django 4.1.2 on 2022-10-05 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ewaevent',
            old_name='user',
            new_name='lc_representative',
        ),
    ]
