# Generated by Django 4.1.2 on 2022-10-05 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_rename_user_ewaevent_lc_representative'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lc_representative', models.CharField(max_length=50)),
                ('lc_name', models.CharField(max_length=50)),
                ('event_name', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('price', models.IntegerField()),
                ('delegates_number', models.IntegerField()),
                ('status', models.BooleanField(default=False)),
                ('conference_type', models.CharField(choices=[('National', 'National'), ('Local', 'Local')], max_length=50)),
            ],
        ),
    ]
