# Generated by Django 4.1.2 on 2022-10-07 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_ewadelegate'),
    ]

    operations = [
        migrations.AddField(
            model_name='ewadelegate',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='event.ewaevent'),
        ),
    ]
