# Generated by Django 4.1.2 on 2022-10-07 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_ewadelegate_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ewadelegate',
            name='cv',
        ),
        migrations.RemoveField(
            model_name='ewadelegate',
            name='id_back',
        ),
        migrations.RemoveField(
            model_name='ewadelegate',
            name='id_front',
        ),
    ]
