# Generated by Django 4.1.2 on 2022-10-08 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_remove_ewadelegate_cv_remove_ewadelegate_id_back_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ewaevent',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
