# Generated by Django 4.1.2 on 2022-10-08 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_conference_email_sent_ewaevent_email_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='registration_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ewaevent',
            name='registration_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
