# Generated by Django 4.1.2 on 2022-10-10 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_conference_registration_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ewadelegate',
            name='id_back',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='ewadelegate',
            name='id_front',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
