# Generated by Django 4.1.2 on 2022-10-11 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_ewadelegate_id_back_ewadelegate_id_front'),
    ]

    operations = [
        migrations.AddField(
            model_name='ewadelegate',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='ewadelegate',
            name='indemnity_form',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='ewadelegate',
            name='id_back',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='ewadelegate',
            name='id_front',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
