# Generated by Django 4.1.2 on 2022-10-12 02:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0011_ewadelegate_cv_ewadelegate_indemnity_form_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ewadelegate',
            name='aiesecer',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50, verbose_name='AIESECer'),
        ),
        migrations.AlterField(
            model_name='ewadelegate',
            name='lc',
            field=models.CharField(blank=True, choices=[('6TH OCTOBER UNIVERSITY', '6TH OCTOBER UNIVERSITY'), ('AAST ALEXANDRIA', 'AAST ALEXANDRIA'), ('AAST IN CAIRO', 'AAST IN CAIRO'), ('AIN SHAMS UNIVERSITY', 'AIN SHAMS UNIVERSITY'), ('ALEXANDRIA', 'ALEXANDRIA'), ('AUC', 'AUC'), ('BENI SUEF', 'BENI SUEF'), ('CAIRO UNIVERSITY', 'CAIRO UNIVERSITY'), ('DAMIETTA', 'DAMIETTA'), ('GUC', 'GUC'), ('HELWAN', 'HELWAN'), ('LUXOR & ASWAN', 'LUXOR & ASWAN'), ('MANSOURA', 'MANSOURA'), ('MC EGYPT', 'MC EGYPT'), ('MENOFIA', 'MENOFIA'), ('MIU', 'MIU'), ('MSA', 'MSA'), ('MUST', 'MUST'), ('SUEZ', 'SUEZ'), ('TANTA', 'TANTA'), ('ZAGAZIG', 'ZAGAZIG')], max_length=50, null=True, verbose_name='LC'),
        ),
        migrations.AlterField(
            model_name='ewadelegate',
            name='time_stamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='ConferenceDelegate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50)),
                ('phone_number', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('cv', models.FileField(blank=True, null=True, upload_to='')),
                ('indemnity_form', models.FileField(null=True, upload_to='')),
                ('id_front', models.ImageField(null=True, upload_to='')),
                ('id_back', models.ImageField(null=True, upload_to='')),
                ('time_stamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('lc', models.CharField(blank=True, choices=[('6TH OCTOBER UNIVERSITY', '6TH OCTOBER UNIVERSITY'), ('AAST ALEXANDRIA', 'AAST ALEXANDRIA'), ('AAST IN CAIRO', 'AAST IN CAIRO'), ('AIN SHAMS UNIVERSITY', 'AIN SHAMS UNIVERSITY'), ('ALEXANDRIA', 'ALEXANDRIA'), ('AUC', 'AUC'), ('BENI SUEF', 'BENI SUEF'), ('CAIRO UNIVERSITY', 'CAIRO UNIVERSITY'), ('DAMIETTA', 'DAMIETTA'), ('GUC', 'GUC'), ('HELWAN', 'HELWAN'), ('LUXOR & ASWAN', 'LUXOR & ASWAN'), ('MANSOURA', 'MANSOURA'), ('MC EGYPT', 'MC EGYPT'), ('MENOFIA', 'MENOFIA'), ('MIU', 'MIU'), ('MSA', 'MSA'), ('MUST', 'MUST'), ('SUEZ', 'SUEZ'), ('TANTA', 'TANTA'), ('ZAGAZIG', 'ZAGAZIG')], max_length=50, null=True, verbose_name='LC')),
                ('role', models.CharField(blank=True, choices=[('LCP', 'LCP'), ('LCVP', 'LCVP'), ('MM', 'MM'), ('Member', 'Member'), ('Alumni', 'Alumni')], max_length=50, null=True)),
                ('function', models.CharField(blank=True, choices=[('LCP', 'LCP'), ('F&L', 'F&L'), ('MXP', 'MXP'), ('BD', 'BD'), ('B2C', 'B2C'), ('IGV', 'IGV'), ('OGV', 'OGV'), ('IGT', 'IGT'), ('OGT', 'OGT')], max_length=50, null=True)),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='event.conference')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
