# Generated by Django 4.1.2 on 2022-10-12 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0012_alter_ewadelegate_aiesecer_alter_ewadelegate_lc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='ewaevent',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
