# Generated by Django 4.1.2 on 2022-12-12 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0014_localconferencedelegate_nationalconferencedelegate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='localconferencedelegate',
            name='lc',
            field=models.CharField(blank=True, choices=[('6TH OCTOBER UNIVERSITY', '6TH OCTOBER UNIVERSITY'), ('AAST ALEXANDRIA', 'AAST ALEXANDRIA'), ('AAST IN CAIRO', 'AAST IN CAIRO'), ('AIN SHAMS UNIVERSITY', 'AIN SHAMS UNIVERSITY'), ('ALEXANDRIA', 'ALEXANDRIA'), ('AUC', 'AUC'), ('BENI SUEF', 'BENI SUEF'), ('CAIRO UNIVERSITY', 'CAIRO UNIVERSITY'), ('DAMIETTA', 'DAMIETTA'), ('GUC', 'GUC'), ('HELWAN', 'HELWAN'), ('LUXOR & ASWAN', 'LUXOR & ASWAN'), ('MANSOURA', 'MANSOURA'), ('MC EGYPT', 'MC EGYPT'), ('MENOFIA', 'MENOFIA'), ('MIU', 'MIU'), ('MSA', 'MSA'), ('MUST', 'MUST'), ('SUEZ', 'SUEZ'), ('TANTA', 'TANTA'), ('ZAGAZIG', 'ZAGAZIG')], max_length=50, null=True, verbose_name='LC'),
        ),
    ]
