# Generated by Django 4.1.2 on 2023-01-05 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0015_localconferencedelegate_lc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conference',
            name='registration_link',
        ),
        migrations.RemoveField(
            model_name='ewaevent',
            name='registration_link',
        ),
        migrations.AddField(
            model_name='conference',
            name='random_url',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='ewaevent',
            name='random_url',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='conference',
            name='event_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='ewaevent',
            name='event_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
