# Generated by Django 4.1.2 on 2023-01-05 12:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0017_remove_conference_random_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='random_id',
            field=models.CharField(default=uuid.UUID('5946c921-8cb9-42af-b981-86c27bf7cf17'), max_length=200),
        ),
        migrations.AddField(
            model_name='ewaevent',
            name='random_id',
            field=models.CharField(default=uuid.UUID('5946c921-8cb9-42af-b981-86c27bf7cf17'), max_length=200),
        ),
    ]
