# Generated by Django 4.1.2 on 2023-01-05 12:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0018_conference_random_id_ewaevent_random_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='random_id',
            field=models.CharField(default=uuid.UUID('e66ef5ea-65ba-4a36-b316-8959cef3fe1d'), max_length=200),
        ),
        migrations.AlterField(
            model_name='ewaevent',
            name='random_id',
            field=models.CharField(default=uuid.UUID('e66ef5ea-65ba-4a36-b316-8959cef3fe1d'), max_length=200),
        ),
    ]
