# Generated by Django 4.1.2 on 2023-01-05 12:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0019_alter_conference_random_id_alter_ewaevent_random_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ewaevent',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conference',
            name='random_id',
            field=models.CharField(default=uuid.UUID('ff3b0707-98de-4fb5-93cc-3bfcdc873bdc'), max_length=200),
        ),
        migrations.AlterField(
            model_name='ewaevent',
            name='random_id',
            field=models.CharField(default=uuid.UUID('ff3b0707-98de-4fb5-93cc-3bfcdc873bdc'), max_length=200),
        ),
    ]
