# Generated by Django 4.1.2 on 2023-01-16 01:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0021_entity_alter_conference_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='random_id',
            field=models.CharField(default=uuid.UUID('3be95b6e-aa51-474b-b1c8-1c35d76399a3'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='ewaevent',
            name='random_id',
            field=models.CharField(default=uuid.UUID('3be95b6e-aa51-474b-b1c8-1c35d76399a3'), max_length=200, unique=True),
        ),
    ]
