# Generated by Django 4.1.2 on 2023-01-16 02:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0022_alter_conference_random_id_alter_ewaevent_random_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='random_id',
            field=models.CharField(default=uuid.UUID('91cabd5d-c54d-45df-af6f-bd213beab872'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='ewaevent',
            name='random_id',
            field=models.CharField(default=uuid.UUID('91cabd5d-c54d-45df-af6f-bd213beab872'), max_length=200, unique=True),
        ),
    ]
