# Generated by Django 4.1.2 on 2023-01-16 17:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0023_alter_conference_random_id_alter_ewaevent_random_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='host_lc',
        ),
        migrations.AddField(
            model_name='profile',
            name='home_lc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.entity'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='random_id',
            field=models.CharField(default=uuid.UUID('833f9073-611a-4fd8-94aa-8ed5ce4c5b94'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='ewaevent',
            name='random_id',
            field=models.CharField(default=uuid.UUID('833f9073-611a-4fd8-94aa-8ed5ce4c5b94'), max_length=200, unique=True),
        ),
    ]
