# Generated by Django 4.1.2 on 2023-01-16 17:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0024_remove_profile_host_lc_profile_home_lc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='random_id',
            field=models.CharField(default=uuid.UUID('ca021342-0e3d-4e96-96bc-47ff792fe2f1'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='ewaevent',
            name='random_id',
            field=models.CharField(default=uuid.UUID('ca021342-0e3d-4e96-96bc-47ff792fe2f1'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='home_lc',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
