# Generated by Django 4.1.2 on 2023-01-21 11:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0026_alter_conference_random_id_alter_ewaevent_random_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='conference',
            name='random_id',
            field=models.CharField(default=uuid.UUID('1386f39b-affd-438b-8c6b-8ce599c9a084'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='ewaevent',
            name='random_id',
            field=models.CharField(default=uuid.UUID('1386f39b-affd-438b-8c6b-8ce599c9a084'), max_length=200, unique=True),
        ),
    ]
